packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  unrs-resolver: false

catalog:
  typescript: ^5.9.3
  eslint: ^9.39.5
  "@eslint/js": ^9.39.5
  typescript-eslint: ^8.70.0
  globals: ^16.5.0
  vitest: ^3.2.7
  "@types/node": ^24.10.0
  zod: ^4.6.5

minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.10.13'
  - '@turbo/darwin-arm64@2.10.13'
  - '@turbo/linux-64@2.10.13'
  - '@turbo/linux-arm64@2.10.13'
  - '@turbo/windows-64@2.10.13'
  - '@turbo/windows-arm64@2.10.13'
  - turbo@2.10.13
  - '@heroui/react@3.2.6'
  - '@heroui/styles@3.2.6'
